---
- hosts: checkpoint
  connection: httpapi
  gather_facts: False
  tasks:
    - name: task to add access rules 
      cp_mgmt_access_rule:
        layer: Network
        name: Rule 1
        position: 1
        service:
          - SMTP
          - AOL
        state: present
    - name: task to delete-access-rule
      cp_mgmt_access_rule:
        layer: Network
        name: Rule 1
        state: absent
