---
- hosts: checkpoint
  gather_facts: no
  connection: httpapi
  tasks:
  - name: show-threat-rulebase
    cp_mgmt_threat_rule_facts:
      name: test_rule_new_1
      layer: xxxx-abw2-466c-9735-xxxyyyssss223
