---
- hosts: ios
  gather_facts: no

  vars:
    log_servers:
      - logging 8.8.8.8
      - logging 9.9.9.9


  tasks:

  - name: get the current log server configs
    ios_command:
      commands:
        - show running-config full | include logging
    register: log

  - debug: var=log.stdout_lines


  - name: set logging commands
    ios_config:
      commands: "{{ item }}"
    loop: "{{ log_servers }}"
    register: set_logging


  - name: get the new log server configs
    ios_command:
      commands:
        - show running-config full | include logging
    register: log1

  - debug: var=log1.stdout_lines

